---
# tasks file for mongodb
#- name: Add Mongo packages repo
 # apt_key: id=2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5  keyserver=keyserver.ubuntu.com

#- name: add repo itself
  #apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu {{ansible_distribution_release}}/mongodb-org/3.4 multiverse' state=present                                      

#- name: install packages
 # apt: pkg=mongodb-org state=present

- name: Import MongoDB public GPG Key
  apt_key:
        keyserver: keyserver.ubuntu.com
        id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
- name: Add MongoDB repository into sources list
  apt_repository:
      filename: '/etc/apr/sources.list.d/mongodb-org-3.2.list' 
      #repo: deb http://repo.mongodb.org/apt/ubuntu {{ansible_distribution_release}}/mongodb-org/3.4 multiverse
      repo: "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse"
      state: present
- name: Install MongoDB package
  apt:
    name: mongodb
    update_cache: yes
    #become: yes